# Generated by Django 5.2.1 on 2025-05-12 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Dino', '0002_carrito_fecha_actualizacion_carrito_fecha_creacion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carrito',
            name='usuario',
        ),
    ]
